spring.datasource.url=${FOODMANAGER_DB_URL:jdbc:postgresql://localhost:5432/foodmanager}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${FOODMANAGER_DB_USER:foodmanager}
spring.datasource.password=${FOODMANAGER_DB_PASSWORD:foodmanager}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

