spring.application.name=foodmanager

server.port=8085

spring.datasource.url=jdbc:h2:file:./data/foodmanager-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

foodmanager.storage.image-dir=./data/images
foodmanager.expiring-soon-days=7

spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID:foodmanager-web}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:foodmanager-web-secret}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/foodmanager}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

